name: etoile_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_cube: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/test_banniere.jpg
    - json/rooms.json
    - json/doors.json
    - json/windows.json
    - obj/floor_1_rooms.obj
    - obj/floor_1_doors.obj
    - obj/floor_1_windows.obj
    - obj/floor_2_rooms.obj
    - obj/floor_2_doors.obj
    - obj/floor_2_windows.obj
    - obj/floor_3_rooms.obj
    - obj/floor_3_doors.obj
    - obj/floor_3_windows.obj
    - obj/floor_4_rooms.obj
    - obj/floor_4_doors.obj
    - obj/floor_4_windows.obj
    - obj/floor_colors.mtl